#! /usr/bin/python
import sys
from PyQt4 import Qt

import disamiqo_qrc
import disamiqotray

__version__ = "1.0.0"

if __name__ == '__main__':

    app = Qt.QApplication(sys.argv)
    
    if (not Qt.QSystemTrayIcon.isSystemTrayAvailable()):
        Qt.QMessageBox.critical(0, "DisamiQo",
                                "Couldn't detect any system tray on this system.");
        sys.exit(1)
     

    Qt.QApplication.setQuitOnLastWindowClosed(False)
     
    disamiqo = disamiqotray.DisamiqoTray()
    sys.exit(app.exec_())

