# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fanta.ui'
#
# Created: Sat Feb 11 16:25:50 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_fanta(object):
    def setupUi(self, fanta):
        fanta.setObjectName(_fromUtf8("fanta"))
        fanta.resize(800, 600)
        fanta.setWindowTitle(QtGui.QApplication.translate("fanta", "Fantamanager", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("fanta.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        fanta.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(fanta)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.vboxlayout = QtGui.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.tableGiocatori = QtGui.QTableView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableGiocatori.sizePolicy().hasHeightForWidth())
        self.tableGiocatori.setSizePolicy(sizePolicy)
        self.tableGiocatori.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableGiocatori.setObjectName(_fromUtf8("tableGiocatori"))
        self.hboxlayout.addWidget(self.tableGiocatori)
        self.vboxlayout.addLayout(self.hboxlayout)
        fanta.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fanta)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("fanta", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuModifica = QtGui.QMenu(self.menubar)
        self.menuModifica.setTitle(QtGui.QApplication.translate("fanta", "Modifica", None, QtGui.QApplication.UnicodeUTF8))
        self.menuModifica.setObjectName(_fromUtf8("menuModifica"))
        self.menuGestione = QtGui.QMenu(self.menubar)
        self.menuGestione.setTitle(QtGui.QApplication.translate("fanta", "Gestione", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGestione.setObjectName(_fromUtf8("menuGestione"))
        fanta.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(fanta)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        fanta.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(fanta)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("fanta", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setToolTip(QtGui.QApplication.translate("fanta", "Nuova Formazione", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        fanta.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(fanta)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/folder_orange_open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setText(QtGui.QApplication.translate("fanta", "Apri", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(fanta)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("images/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setText(QtGui.QApplication.translate("fanta", "Salva", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionNew = QtGui.QAction(fanta)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("images/filenew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon3)
        self.actionNew.setText(QtGui.QApplication.translate("fanta", "Nuovo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionChiudi = QtGui.QAction(fanta)
        self.actionChiudi.setText(QtGui.QApplication.translate("fanta", "Chiudi", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChiudi.setObjectName(_fromUtf8("actionChiudi"))
        self.actionNuovo_giocatore = QtGui.QAction(fanta)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("images/add_user.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNuovo_giocatore.setIcon(icon4)
        self.actionNuovo_giocatore.setText(QtGui.QApplication.translate("fanta", "Nuovo Giocatore", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuovo_giocatore.setObjectName(_fromUtf8("actionNuovo_giocatore"))
        self.actionModifica_Giocatore = QtGui.QAction(fanta)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("images/edit_user.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionModifica_Giocatore.setIcon(icon5)
        self.actionModifica_Giocatore.setText(QtGui.QApplication.translate("fanta", "Modifica Giocatore", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModifica_Giocatore.setObjectName(_fromUtf8("actionModifica_Giocatore"))
        self.actionElimina_Giocatore = QtGui.QAction(fanta)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("images/delete_user.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionElimina_Giocatore.setIcon(icon6)
        self.actionElimina_Giocatore.setText(QtGui.QApplication.translate("fanta", "Elimina Giocatore", None, QtGui.QApplication.UnicodeUTF8))
        self.actionElimina_Giocatore.setObjectName(_fromUtf8("actionElimina_Giocatore"))
        self.actionFormazione = QtGui.QAction(fanta)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("images/pencil.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormazione.setIcon(icon7)
        self.actionFormazione.setText(QtGui.QApplication.translate("fanta", "Formazione", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFormazione.setObjectName(_fromUtf8("actionFormazione"))
        self.actionInserisci_Voti = QtGui.QAction(fanta)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("images/math_sum.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInserisci_Voti.setIcon(icon8)
        self.actionInserisci_Voti.setText(QtGui.QApplication.translate("fanta", "Inserisci Voti", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInserisci_Voti.setObjectName(_fromUtf8("actionInserisci_Voti"))
        self.actionProfilo_Squadra = QtGui.QAction(fanta)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("images/contents2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProfilo_Squadra.setIcon(icon9)
        self.actionProfilo_Squadra.setText(QtGui.QApplication.translate("fanta", "Profilo Squadra", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProfilo_Squadra.setObjectName(_fromUtf8("actionProfilo_Squadra"))
        self.actionMedie_Giocatori = QtGui.QAction(fanta)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("images/frac.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMedie_Giocatori.setIcon(icon10)
        self.actionMedie_Giocatori.setText(QtGui.QApplication.translate("fanta", "Medie Giocatori", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMedie_Giocatori.setObjectName(_fromUtf8("actionMedie_Giocatori"))
        self.actionFormazione_tipo = QtGui.QAction(fanta)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("images/package_edutainment.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFormazione_tipo.setIcon(icon11)
        self.actionFormazione_tipo.setText(QtGui.QApplication.translate("fanta", "Formazione tipo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFormazione_tipo.setObjectName(_fromUtf8("actionFormazione_tipo"))
        self.actionAggiorna_Giocatore = QtGui.QAction(fanta)
        self.actionAggiorna_Giocatore.setText(QtGui.QApplication.translate("fanta", "Aggiorna Giocatore", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAggiorna_Giocatore.setObjectName(_fromUtf8("actionAggiorna_Giocatore"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionChiudi)
        self.menuModifica.addAction(self.actionNuovo_giocatore)
        self.menuModifica.addAction(self.actionModifica_Giocatore)
        self.menuModifica.addAction(self.actionElimina_Giocatore)
        self.menuModifica.addAction(self.actionAggiorna_Giocatore)
        self.menuGestione.addAction(self.actionFormazione)
        self.menuGestione.addAction(self.actionMedie_Giocatori)
        self.menuGestione.addAction(self.actionFormazione_tipo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuModifica.menuAction())
        self.menubar.addAction(self.menuGestione.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNuovo_giocatore)
        self.toolBar.addAction(self.actionModifica_Giocatore)
        self.toolBar.addAction(self.actionElimina_Giocatore)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFormazione)
        self.toolBar.addAction(self.actionMedie_Giocatori)
        self.toolBar.addAction(self.actionFormazione_tipo)

        self.retranslateUi(fanta)
        QtCore.QMetaObject.connectSlotsByName(fanta)

    def retranslateUi(self, fanta):
        pass
