# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regolamentodialog.ui'
#
# Created: Wed Jan 19 20:32:37 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_RegolamentoDialog(object):
    def setupUi(self, RegolamentoDialog):
        RegolamentoDialog.setObjectName("RegolamentoDialog")
        RegolamentoDialog.resize(624, 455)
        self.vboxlayout = QtGui.QVBoxLayout(RegolamentoDialog)
        self.vboxlayout.setObjectName("vboxlayout")
        self.tabGiocatori = QtGui.QTabWidget(RegolamentoDialog)
        self.tabGiocatori.setObjectName("tabGiocatori")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.tab_6)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.tableView = QtGui.QTableView(self.tab_6)
        self.tableView.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed)
        self.tableView.setCornerButtonEnabled(False)
        self.tableView.setObjectName("tableView")
        self.hboxlayout.addWidget(self.tableView)
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.pushButton = QtGui.QPushButton(self.tab_6)
        self.pushButton.setObjectName("pushButton")
        self.vboxlayout3.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.tab_6)
        self.pushButton_2.setObjectName("pushButton_2")
        self.vboxlayout3.addWidget(self.pushButton_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout3.addItem(spacerItem)
        self.hboxlayout.addLayout(self.vboxlayout3)
        self.vboxlayout2.addLayout(self.hboxlayout)
        self.vboxlayout1.addLayout(self.vboxlayout2)
        self.tabGiocatori.addTab(self.tab_6, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.layoutWidget = QtGui.QWidget(self.tab_4)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 30, 171, 297))
        self.layoutWidget.setObjectName("layoutWidget")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.layoutWidget)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.vboxlayout4 = QtGui.QVBoxLayout()
        self.vboxlayout4.setObjectName("vboxlayout4")
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.vboxlayout4.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.vboxlayout4.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.vboxlayout4.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.vboxlayout4.addWidget(self.label_14)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.vboxlayout4.addWidget(self.label_15)
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.vboxlayout4.addWidget(self.label_16)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.vboxlayout4.addWidget(self.label_10)
        self.label_24 = QtGui.QLabel(self.layoutWidget)
        self.label_24.setObjectName("label_24")
        self.vboxlayout4.addWidget(self.label_24)
        self.label_25 = QtGui.QLabel(self.layoutWidget)
        self.label_25.setObjectName("label_25")
        self.vboxlayout4.addWidget(self.label_25)
        self.label_26 = QtGui.QLabel(self.layoutWidget)
        self.label_26.setObjectName("label_26")
        self.vboxlayout4.addWidget(self.label_26)
        self.hboxlayout1.addLayout(self.vboxlayout4)
        self.vboxlayout5 = QtGui.QVBoxLayout()
        self.vboxlayout5.setObjectName("vboxlayout5")
        self.spinBox_7 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_7.setProperty("value", 66)
        self.spinBox_7.setObjectName("spinBox_7")
        self.vboxlayout5.addWidget(self.spinBox_7)
        self.spinBox_8 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_8.setProperty("value", 72)
        self.spinBox_8.setObjectName("spinBox_8")
        self.vboxlayout5.addWidget(self.spinBox_8)
        self.spinBox_9 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_9.setProperty("value", 78)
        self.spinBox_9.setObjectName("spinBox_9")
        self.vboxlayout5.addWidget(self.spinBox_9)
        self.spinBox_10 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_10.setProperty("value", 84)
        self.spinBox_10.setObjectName("spinBox_10")
        self.vboxlayout5.addWidget(self.spinBox_10)
        self.spinBox_11 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_11.setProperty("value", 90)
        self.spinBox_11.setObjectName("spinBox_11")
        self.vboxlayout5.addWidget(self.spinBox_11)
        self.spinBox_12 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_12.setProperty("value", 96)
        self.spinBox_12.setObjectName("spinBox_12")
        self.vboxlayout5.addWidget(self.spinBox_12)
        self.spinBox_20 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_20.setMaximum(120)
        self.spinBox_20.setProperty("value", 102)
        self.spinBox_20.setObjectName("spinBox_20")
        self.vboxlayout5.addWidget(self.spinBox_20)
        self.spinBox_21 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_21.setMaximum(120)
        self.spinBox_21.setProperty("value", 108)
        self.spinBox_21.setObjectName("spinBox_21")
        self.vboxlayout5.addWidget(self.spinBox_21)
        self.spinBox_22 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_22.setMaximum(120)
        self.spinBox_22.setProperty("value", 114)
        self.spinBox_22.setObjectName("spinBox_22")
        self.vboxlayout5.addWidget(self.spinBox_22)
        self.spinBox_6 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_6.setMaximum(130)
        self.spinBox_6.setProperty("value", 120)
        self.spinBox_6.setObjectName("spinBox_6")
        self.vboxlayout5.addWidget(self.spinBox_6)
        self.hboxlayout1.addLayout(self.vboxlayout5)
        self.tabGiocatori.addTab(self.tab_4, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.label_27 = QtGui.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(40, 150, 159, 18))
        self.label_27.setObjectName("label_27")
        self.layoutWidget1 = QtGui.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(240, 40, 111, 281))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.vboxlayout6 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.vboxlayout6.setObjectName("vboxlayout6")
        self.checkBox_10 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_10.setObjectName("checkBox_10")
        self.vboxlayout6.addWidget(self.checkBox_10)
        self.checkBox_2 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_2.setObjectName("checkBox_2")
        self.vboxlayout6.addWidget(self.checkBox_2)
        self.checkBox_3 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_3.setObjectName("checkBox_3")
        self.vboxlayout6.addWidget(self.checkBox_3)
        self.checkBox_4 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_4.setObjectName("checkBox_4")
        self.vboxlayout6.addWidget(self.checkBox_4)
        self.checkBox_5 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_5.setObjectName("checkBox_5")
        self.vboxlayout6.addWidget(self.checkBox_5)
        self.checkBox_6 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_6.setObjectName("checkBox_6")
        self.vboxlayout6.addWidget(self.checkBox_6)
        self.checkBox_7 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_7.setObjectName("checkBox_7")
        self.vboxlayout6.addWidget(self.checkBox_7)
        self.checkBox_11 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_11.setObjectName("checkBox_11")
        self.vboxlayout6.addWidget(self.checkBox_11)
        self.checkBox_8 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_8.setObjectName("checkBox_8")
        self.vboxlayout6.addWidget(self.checkBox_8)
        self.tabGiocatori.addTab(self.tab, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.layoutWidget2 = QtGui.QWidget(self.tab_5)
        self.layoutWidget2.setGeometry(QtCore.QRect(290, 50, 191, 72))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.vboxlayout7 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.vboxlayout7.setObjectName("vboxlayout7")
        self.checkBox_9 = QtGui.QCheckBox(self.layoutWidget2)
        self.checkBox_9.setObjectName("checkBox_9")
        self.vboxlayout7.addWidget(self.checkBox_9)
        self.checkBox_13 = QtGui.QCheckBox(self.layoutWidget2)
        self.checkBox_13.setObjectName("checkBox_13")
        self.vboxlayout7.addWidget(self.checkBox_13)
        self.checkBox_12 = QtGui.QCheckBox(self.layoutWidget2)
        self.checkBox_12.setObjectName("checkBox_12")
        self.vboxlayout7.addWidget(self.checkBox_12)
        self.layoutWidget3 = QtGui.QWidget(self.tab_5)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 20, 211, 331))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridlayout = QtGui.QGridLayout(self.layoutWidget3)
        self.gridlayout.setObjectName("gridlayout")
        self.label_23 = QtGui.QLabel(self.layoutWidget3)
        self.label_23.setObjectName("label_23")
        self.gridlayout.addWidget(self.label_23, 0, 0, 1, 1)
        self.spinBox_19 = QtGui.QSpinBox(self.layoutWidget3)
        self.spinBox_19.setMinimum(-10)
        self.spinBox_19.setProperty("value", -1)
        self.spinBox_19.setObjectName("spinBox_19")
        self.gridlayout.addWidget(self.spinBox_19, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget3)
        self.label_17.setObjectName("label_17")
        self.gridlayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.spinBox_13 = QtGui.QSpinBox(self.layoutWidget3)
        self.spinBox_13.setProperty("value", 3)
        self.spinBox_13.setObjectName("spinBox_13")
        self.gridlayout.addWidget(self.spinBox_13, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget3)
        self.label_18.setObjectName("label_18")
        self.gridlayout.addWidget(self.label_18, 2, 0, 1, 1)
        self.spinBox_14 = QtGui.QSpinBox(self.layoutWidget3)
        self.spinBox_14.setMinimum(-10)
        self.spinBox_14.setProperty("value", -3)
        self.spinBox_14.setObjectName("spinBox_14")
        self.gridlayout.addWidget(self.spinBox_14, 2, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget3)
        self.label_19.setObjectName("label_19")
        self.gridlayout.addWidget(self.label_19, 3, 0, 1, 1)
        self.spinBox_15 = QtGui.QSpinBox(self.layoutWidget3)
        self.spinBox_15.setProperty("value", 3)
        self.spinBox_15.setObjectName("spinBox_15")
        self.gridlayout.addWidget(self.spinBox_15, 3, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget3)
        self.label_20.setObjectName("label_20")
        self.gridlayout.addWidget(self.label_20, 4, 0, 1, 1)
        self.spinBox_16 = QtGui.QSpinBox(self.layoutWidget3)
        self.spinBox_16.setProperty("value", 1)
        self.spinBox_16.setObjectName("spinBox_16")
        self.gridlayout.addWidget(self.spinBox_16, 4, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.layoutWidget3)
        self.label_21.setObjectName("label_21")
        self.gridlayout.addWidget(self.label_21, 5, 0, 1, 1)
        self.spinBox_17 = QtGui.QSpinBox(self.layoutWidget3)
        self.spinBox_17.setMinimum(-10)
        self.spinBox_17.setSingleStep(1)
        self.spinBox_17.setProperty("value", -1)
        self.spinBox_17.setObjectName("spinBox_17")
        self.gridlayout.addWidget(self.spinBox_17, 5, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.layoutWidget3)
        self.label_22.setObjectName("label_22")
        self.gridlayout.addWidget(self.label_22, 6, 0, 1, 1)
        self.spinBox_18 = QtGui.QSpinBox(self.layoutWidget3)
        self.spinBox_18.setMinimum(-10)
        self.spinBox_18.setProperty("value", -1)
        self.spinBox_18.setObjectName("spinBox_18")
        self.gridlayout.addWidget(self.spinBox_18, 6, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.layoutWidget3)
        self.label_28.setObjectName("label_28")
        self.gridlayout.addWidget(self.label_28, 7, 0, 1, 1)
        self.spinBox_23 = QtGui.QSpinBox(self.layoutWidget3)
        self.spinBox_23.setProperty("value", 3)
        self.spinBox_23.setObjectName("spinBox_23")
        self.gridlayout.addWidget(self.spinBox_23, 7, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.layoutWidget3)
        self.label_29.setObjectName("label_29")
        self.gridlayout.addWidget(self.label_29, 8, 0, 1, 1)
        self.spinBox_24 = QtGui.QSpinBox(self.layoutWidget3)
        self.spinBox_24.setMinimum(-10)
        self.spinBox_24.setProperty("value", -2)
        self.spinBox_24.setObjectName("spinBox_24")
        self.gridlayout.addWidget(self.spinBox_24, 8, 1, 1, 1)
        self.tabGiocatori.addTab(self.tab_5, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.spinBox_5 = QtGui.QSpinBox(self.tab_2)
        self.spinBox_5.setGeometry(QtCore.QRect(130, 30, 50, 23))
        self.spinBox_5.setObjectName("spinBox_5")
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 107, 18))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 56, 18))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 56, 18))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(10, 150, 56, 18))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(10, 190, 56, 18))
        self.label_9.setObjectName("label_9")
        self.tabGiocatori.addTab(self.tab_2, "")
        self.vboxlayout.addWidget(self.tabGiocatori)
        self.buttonBox = QtGui.QDialogButtonBox(RegolamentoDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.NoButton|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(RegolamentoDialog)
        self.tabGiocatori.setCurrentIndex(2)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), RegolamentoDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), RegolamentoDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RegolamentoDialog)

    def retranslateUi(self, RegolamentoDialog):
        RegolamentoDialog.setWindowTitle(QtGui.QApplication.translate("RegolamentoDialog", "Regolamento", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("RegolamentoDialog", "Nuovo", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("RegolamentoDialog", "Rimuovi", None, QtGui.QApplication.UnicodeUTF8))
        self.tabGiocatori.setTabText(self.tabGiocatori.indexOf(self.tab_6), QtGui.QApplication.translate("RegolamentoDialog", "Giocatori", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("RegolamentoDialog", "1 Goal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("RegolamentoDialog", "2 Goal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("RegolamentoDialog", "3 Goal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("RegolamentoDialog", "4 Goal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("RegolamentoDialog", "5 Goal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("RegolamentoDialog", "6 Goal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("RegolamentoDialog", "7 Goal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("RegolamentoDialog", "8 Goal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("RegolamentoDialog", "9 Goal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("RegolamentoDialog", "10 Goal", None, QtGui.QApplication.UnicodeUTF8))
        self.tabGiocatori.setTabText(self.tabGiocatori.indexOf(self.tab_4), QtGui.QApplication.translate("RegolamentoDialog", "Punteggi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("RegolamentoDialog", "Schemi di gioco consentiti", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_10.setText(QtGui.QApplication.translate("RegolamentoDialog", "6-3-1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("RegolamentoDialog", "5-4-1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("RegolamentoDialog", "5-3-2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("RegolamentoDialog", "4-5-1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("RegolamentoDialog", "4-4-2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("RegolamentoDialog", "4-3-3", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("RegolamentoDialog", "3-6-1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_11.setText(QtGui.QApplication.translate("RegolamentoDialog", "3-5-2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("RegolamentoDialog", "3-4-3", None, QtGui.QApplication.UnicodeUTF8))
        self.tabGiocatori.setTabText(self.tabGiocatori.indexOf(self.tab), QtGui.QApplication.translate("RegolamentoDialog", "Schemi", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setText(QtGui.QApplication.translate("RegolamentoDialog", "6 politico a s.v.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_13.setText(QtGui.QApplication.translate("RegolamentoDialog", "sost. \"automatica\" portiere", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_12.setText(QtGui.QApplication.translate("RegolamentoDialog", "Portiere s.v. = 6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("RegolamentoDialog", "Goal Subito", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("RegolamentoDialog", "Rigore Parato", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("RegolamentoDialog", "Rigore Sbagliato", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("RegolamentoDialog", "Goal Segnato", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("RegolamentoDialog", "Assist", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("RegolamentoDialog", "Ammonizione", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_17.setSuffix(QtGui.QApplication.translate("RegolamentoDialog", " * 0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("RegolamentoDialog", "Espulsione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("RegolamentoDialog", "Rigore Segnato", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("RegolamentoDialog", "Autogoal", None, QtGui.QApplication.UnicodeUTF8))
        self.tabGiocatori.setTabText(self.tabGiocatori.indexOf(self.tab_5), QtGui.QApplication.translate("RegolamentoDialog", "Punteggi Giocatori", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("RegolamentoDialog", "Fattore campo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("RegolamentoDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("RegolamentoDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("RegolamentoDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("RegolamentoDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabGiocatori.setTabText(self.tabGiocatori.indexOf(self.tab_2), QtGui.QApplication.translate("RegolamentoDialog", "Vantaggi", None, QtGui.QApplication.UnicodeUTF8))

