#! /usr/bin/env python

import sys
from PyQt4.QtGui import *
from PyQt4.QtCore import *

from main_kdarts import MainDialog

if __name__ == "__main__":  
    app = QApplication(sys.argv)
    
    main_window = MainDialog()

    main_window.show()
    sys.exit(app.exec_())
