#! /usr/bin/env python

import sys
import MySQLdb
from PyQt4.QtGui import *
from PyQt4.QtCore import *

from main import MainDialog

if __name__ == "__main__":  
    app = QApplication(sys.argv)

    text = QInputDialog.getText(QDialog(), "Force 10 DB Connection",
                                "Password:", QLineEdit.Password);
    
    if (text[1]):
        db = MySQLdb.connect(host="localhost", user="sani",
                             passwd='%s' % text[0],
                             db="force_10")
    
    main_window = MainDialog(db)

    main_window.show()
    sys.exit(app.exec_())
