# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tdpalio.ui'
#
# Created: Mon May 24 21:54:10 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 643)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("tdp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtGui.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tableWidget_contrade = QtGui.QTableWidget(self.frame)
        self.tableWidget_contrade.setGeometry(QtCore.QRect(540, 261, 261, 238))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_contrade.sizePolicy().hasHeightForWidth())
        self.tableWidget_contrade.setSizePolicy(sizePolicy)
        self.tableWidget_contrade.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget_contrade.setMaximumSize(QtCore.QSize(16777215, 238))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.tableWidget_contrade.setFont(font)
        self.tableWidget_contrade.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_contrade.setAutoScroll(False)
        self.tableWidget_contrade.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidget_contrade.setIconSize(QtCore.QSize(20, 20))
        self.tableWidget_contrade.setShowGrid(True)
        self.tableWidget_contrade.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_contrade.setWordWrap(False)
        self.tableWidget_contrade.setCornerButtonEnabled(False)
        self.tableWidget_contrade.setRowCount(10)
        self.tableWidget_contrade.setObjectName("tableWidget_contrade")
        self.tableWidget_contrade.setColumnCount(3)
        self.tableWidget_contrade.setRowCount(10)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_contrade.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_contrade.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_contrade.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_contrade.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_contrade.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_contrade.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_contrade.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_contrade.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_contrade.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_contrade.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_contrade.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_contrade.setHorizontalHeaderItem(2, item)
        self.graphicsView = QtGui.QGraphicsView(self.frame)
        self.graphicsView.setEnabled(False)
        self.graphicsView.setGeometry(QtCore.QRect(8, 8, 501, 483))
        self.graphicsView.setObjectName("graphicsView")
        self.chatEdit = QtGui.QTextEdit(self.frame)
        self.chatEdit.setEnabled(True)
        self.chatEdit.setGeometry(QtCore.QRect(20, 20, 241, 81))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatEdit.sizePolicy().hasHeightForWidth())
        self.chatEdit.setSizePolicy(sizePolicy)
        self.chatEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.chatEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.chatEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chatEdit.setReadOnly(True)
        self.chatEdit.setObjectName("chatEdit")
        self.tabWidget_Panel = QtGui.QTabWidget(self.frame)
        self.tabWidget_Panel.setGeometry(QtCore.QRect(550, 10, 251, 211))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_Panel.sizePolicy().hasHeightForWidth())
        self.tabWidget_Panel.setSizePolicy(sizePolicy)
        self.tabWidget_Panel.setObjectName("tabWidget_Panel")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 217, 94))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_pngContrada = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pngContrada.sizePolicy().hasHeightForWidth())
        self.label_pngContrada.setSizePolicy(sizePolicy)
        self.label_pngContrada.setMinimumSize(QtCore.QSize(50, 50))
        self.label_pngContrada.setMaximumSize(QtCore.QSize(50, 50))
        self.label_pngContrada.setObjectName("label_pngContrada")
        self.horizontalLayout.addWidget(self.label_pngContrada)
        self.label_nomeContrada = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_nomeContrada.sizePolicy().hasHeightForWidth())
        self.label_nomeContrada.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_nomeContrada.setFont(font)
        self.label_nomeContrada.setObjectName("label_nomeContrada")
        self.horizontalLayout.addWidget(self.label_nomeContrada)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_carica = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_carica.sizePolicy().hasHeightForWidth())
        self.label_carica.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_carica.setFont(font)
        self.label_carica.setObjectName("label_carica")
        self.verticalLayout.addWidget(self.label_carica)
        self.label_gradimento = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_gradimento.sizePolicy().hasHeightForWidth())
        self.label_gradimento.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_gradimento.setFont(font)
        self.label_gradimento.setObjectName("label_gradimento")
        self.verticalLayout.addWidget(self.label_gradimento)
        self.tabWidget_Panel.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget1 = QtGui.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 20, 96, 58))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_fantino = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fantino.sizePolicy().hasHeightForWidth())
        self.label_fantino.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_fantino.setFont(font)
        self.label_fantino.setObjectName("label_fantino")
        self.verticalLayout_3.addWidget(self.label_fantino)
        self.label_fantinoCorsi = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fantinoCorsi.sizePolicy().hasHeightForWidth())
        self.label_fantinoCorsi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_fantinoCorsi.setFont(font)
        self.label_fantinoCorsi.setObjectName("label_fantinoCorsi")
        self.verticalLayout_3.addWidget(self.label_fantinoCorsi)
        self.label_fantinoVinti = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fantinoVinti.sizePolicy().hasHeightForWidth())
        self.label_fantinoVinti.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_fantinoVinti.setFont(font)
        self.label_fantinoVinti.setObjectName("label_fantinoVinti")
        self.verticalLayout_3.addWidget(self.label_fantinoVinti)
        self.tabWidget_Panel.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget2 = QtGui.QWidget(self.tab_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 30, 179, 87))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_cavallo = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_cavallo.setFont(font)
        self.label_cavallo.setObjectName("label_cavallo")
        self.verticalLayout_2.addWidget(self.label_cavallo)
        self.label_cavalloCorsi = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_cavalloCorsi.setFont(font)
        self.label_cavalloCorsi.setObjectName("label_cavalloCorsi")
        self.verticalLayout_2.addWidget(self.label_cavalloCorsi)
        self.label_cavalloVinti = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_cavalloVinti.setFont(font)
        self.label_cavalloVinti.setObjectName("label_cavalloVinti")
        self.verticalLayout_2.addWidget(self.label_cavalloVinti)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.progressBar_forma = QtGui.QProgressBar(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.progressBar_forma.setFont(font)
        self.progressBar_forma.setProperty("value", 24)
        self.progressBar_forma.setObjectName("progressBar_forma")
        self.horizontalLayout_2.addWidget(self.progressBar_forma)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget_Panel.addTab(self.tab_3, "")
        self.lineEdit_chat = QtGui.QLineEdit(self.frame)
        self.lineEdit_chat.setEnabled(True)
        self.lineEdit_chat.setGeometry(QtCore.QRect(100, 410, 331, 29))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_chat.sizePolicy().hasHeightForWidth())
        self.lineEdit_chat.setSizePolicy(sizePolicy)
        self.lineEdit_chat.setObjectName("lineEdit_chat")
        self.vboxlayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuInserisci = QtGui.QMenu(self.menubar)
        self.menuInserisci.setObjectName("menuInserisci")
        self.menuOpzioni = QtGui.QMenu(self.menubar)
        self.menuOpzioni.setObjectName("menuOpzioni")
        self.menuServer = QtGui.QMenu(self.menubar)
        self.menuServer.setObjectName("menuServer")
        self.menuTabelle = QtGui.QMenu(self.menubar)
        self.menuTabelle.setObjectName("menuTabelle")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/pictures/filenew.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionPrint = QtGui.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionInserisci_Giocatore = QtGui.QAction(MainWindow)
        self.actionInserisci_Giocatore.setObjectName("actionInserisci_Giocatore")
        self.actionEffetti_sonori = QtGui.QAction(MainWindow)
        self.actionEffetti_sonori.setCheckable(True)
        self.actionEffetti_sonori.setChecked(True)
        self.actionEffetti_sonori.setObjectName("actionEffetti_sonori")
        self.actionAvanti = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/pictures/avanti.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAvanti.setIcon(icon2)
        self.actionAvanti.setObjectName("actionAvanti")
        self.actionConnessione = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/pictures/connect_no.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnessione.setIcon(icon3)
        self.actionConnessione.setObjectName("actionConnessione")
        self.actionAvvia_gioco = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/pictures/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAvvia_gioco.setIcon(icon4)
        self.actionAvvia_gioco.setObjectName("actionAvvia_gioco")
        self.actionScegli_Contrada = QtGui.QAction(MainWindow)
        self.actionScegli_Contrada.setObjectName("actionScegli_Contrada")
        self.actionSpettatore = QtGui.QAction(MainWindow)
        self.actionSpettatore.setObjectName("actionSpettatore")
        self.actionContrada = QtGui.QAction(MainWindow)
        self.actionContrada.setObjectName("actionContrada")
        self.actionVittorie = QtGui.QAction(MainWindow)
        self.actionVittorie.setObjectName("actionVittorie")
        self.actionCuffia = QtGui.QAction(MainWindow)
        self.actionCuffia.setObjectName("actionCuffia")
        self.actionFantini = QtGui.QAction(MainWindow)
        self.actionFantini.setObjectName("actionFantini")
        self.actionCavalli = QtGui.QAction(MainWindow)
        self.actionCavalli.setObjectName("actionCavalli")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionExit)
        self.menuInserisci.addAction(self.actionInserisci_Giocatore)
        self.menuOpzioni.addAction(self.actionEffetti_sonori)
        self.menuServer.addAction(self.actionAvvia_gioco)
        self.menuServer.addAction(self.actionScegli_Contrada)
        self.menuServer.addAction(self.actionSpettatore)
        self.menuTabelle.addAction(self.actionContrada)
        self.menuTabelle.addAction(self.actionVittorie)
        self.menuTabelle.addAction(self.actionCuffia)
        self.menuTabelle.addAction(self.actionFantini)
        self.menuTabelle.addAction(self.actionCavalli)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInserisci.menuAction())
        self.menubar.addAction(self.menuOpzioni.menuAction())
        self.menubar.addAction(self.menuServer.menuAction())
        self.menubar.addAction(self.menuTabelle.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionAvanti)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConnessione)
        self.toolBar.addAction(self.actionAvvia_gioco)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.tabWidget_Panel.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_contrade.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_contrade.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_contrade.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_contrade.verticalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_contrade.verticalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_contrade.verticalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_contrade.verticalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_contrade.verticalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_contrade.verticalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_contrade.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_contrade.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_contrade.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pngContrada.setText(QtGui.QApplication.translate("MainWindow", "Pic", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nomeContrada.setText(QtGui.QApplication.translate("MainWindow", "Imperiale Contrada della Giraffa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_carica.setText(QtGui.QApplication.translate("MainWindow", "Mandato:3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_gradimento.setText(QtGui.QApplication.translate("MainWindow", "Gradimento: 100%", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Panel.setTabText(self.tabWidget_Panel.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Contrada", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fantino.setText(QtGui.QApplication.translate("MainWindow", "Fantino: Gazzelloro", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fantinoCorsi.setText(QtGui.QApplication.translate("MainWindow", "Corsi: 40", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fantinoVinti.setText(QtGui.QApplication.translate("MainWindow", "Vinti: 10", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Panel.setTabText(self.tabWidget_Panel.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Fantino", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cavallo.setText(QtGui.QApplication.translate("MainWindow", "Cavallo: Saltalamacchia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cavalloCorsi.setText(QtGui.QApplication.translate("MainWindow", "Corsi: 40", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cavalloVinti.setText(QtGui.QApplication.translate("MainWindow", "Vinti: 20", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_Panel.setTabText(self.tabWidget_Panel.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Cavallo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInserisci.setTitle(QtGui.QApplication.translate("MainWindow", "Inserisci", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpzioni.setTitle(QtGui.QApplication.translate("MainWindow", "Opzioni", None, QtGui.QApplication.UnicodeUTF8))
        self.menuServer.setTitle(QtGui.QApplication.translate("MainWindow", "Server", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTabelle.setTitle(QtGui.QApplication.translate("MainWindow", "Tabelle", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("MainWindow", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInserisci_Giocatore.setText(QtGui.QApplication.translate("MainWindow", "Giocatore", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEffetti_sonori.setText(QtGui.QApplication.translate("MainWindow", "Effetti sonori", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAvanti.setText(QtGui.QApplication.translate("MainWindow", "Avanti", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnessione.setText(QtGui.QApplication.translate("MainWindow", "Connessione", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAvvia_gioco.setText(QtGui.QApplication.translate("MainWindow", "Avvia gioco", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScegli_Contrada.setText(QtGui.QApplication.translate("MainWindow", "Scegli Contrada", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpettatore.setText(QtGui.QApplication.translate("MainWindow", "Spettatore", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContrada.setText(QtGui.QApplication.translate("MainWindow", "Contrada", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVittorie.setText(QtGui.QApplication.translate("MainWindow", "Vittorie", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCuffia.setText(QtGui.QApplication.translate("MainWindow", "Cuffia", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFantini.setText(QtGui.QApplication.translate("MainWindow", "Fantini", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCavalli.setText(QtGui.QApplication.translate("MainWindow", "Cavalli", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc
