# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'strategiaprove.ui'
#
# Created: Sun Jun 27 15:02:26 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_StrategiaProve(object):
    def setupUi(self, StrategiaProve):
        StrategiaProve.setObjectName("StrategiaProve")
        StrategiaProve.resize(437, 404)
        self.vboxlayout = QtGui.QVBoxLayout(StrategiaProve)
        self.vboxlayout.setObjectName("vboxlayout")
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.contradaLabel = QtGui.QLabel(StrategiaProve)
        self.contradaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.contradaLabel.setWordWrap(False)
        self.contradaLabel.setObjectName("contradaLabel")
        self.vboxlayout1.addWidget(self.contradaLabel)
        self.montaLabel = QtGui.QLabel(StrategiaProve)
        self.montaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.montaLabel.setWordWrap(False)
        self.montaLabel.setObjectName("montaLabel")
        self.vboxlayout1.addWidget(self.montaLabel)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.hboxlayout.addLayout(self.vboxlayout2)
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.provaBox = QtGui.QGroupBox(StrategiaProve)
        self.provaBox.setObjectName("provaBox")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.provaBox)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.vboxlayout4 = QtGui.QVBoxLayout()
        self.vboxlayout4.setObjectName("vboxlayout4")
        self.primaLabel = QtGui.QLabel(self.provaBox)
        self.primaLabel.setWordWrap(False)
        self.primaLabel.setObjectName("primaLabel")
        self.vboxlayout4.addWidget(self.primaLabel)
        self.secondaLabel = QtGui.QLabel(self.provaBox)
        self.secondaLabel.setWordWrap(False)
        self.secondaLabel.setObjectName("secondaLabel")
        self.vboxlayout4.addWidget(self.secondaLabel)
        self.terzaLabel = QtGui.QLabel(self.provaBox)
        self.terzaLabel.setWordWrap(False)
        self.terzaLabel.setObjectName("terzaLabel")
        self.vboxlayout4.addWidget(self.terzaLabel)
        self.quartaLabel = QtGui.QLabel(self.provaBox)
        self.quartaLabel.setWordWrap(False)
        self.quartaLabel.setObjectName("quartaLabel")
        self.vboxlayout4.addWidget(self.quartaLabel)
        self.generaleLabel = QtGui.QLabel(self.provaBox)
        self.generaleLabel.setWordWrap(False)
        self.generaleLabel.setObjectName("generaleLabel")
        self.vboxlayout4.addWidget(self.generaleLabel)
        self.acciaLabel = QtGui.QLabel(self.provaBox)
        self.acciaLabel.setWordWrap(False)
        self.acciaLabel.setObjectName("acciaLabel")
        self.vboxlayout4.addWidget(self.acciaLabel)
        self.hboxlayout2.addLayout(self.vboxlayout4)
        self.vboxlayout5 = QtGui.QVBoxLayout()
        self.vboxlayout5.setObjectName("vboxlayout5")
        self.primaCombo = QtGui.QComboBox(self.provaBox)
        self.primaCombo.setObjectName("primaCombo")
        self.vboxlayout5.addWidget(self.primaCombo)
        self.secondaCombo = QtGui.QComboBox(self.provaBox)
        self.secondaCombo.setObjectName("secondaCombo")
        self.vboxlayout5.addWidget(self.secondaCombo)
        self.terzaCombo = QtGui.QComboBox(self.provaBox)
        self.terzaCombo.setObjectName("terzaCombo")
        self.vboxlayout5.addWidget(self.terzaCombo)
        self.quartaCombo = QtGui.QComboBox(self.provaBox)
        self.quartaCombo.setObjectName("quartaCombo")
        self.vboxlayout5.addWidget(self.quartaCombo)
        self.generaleCombo = QtGui.QComboBox(self.provaBox)
        self.generaleCombo.setObjectName("generaleCombo")
        self.vboxlayout5.addWidget(self.generaleCombo)
        self.acciaCombo = QtGui.QComboBox(self.provaBox)
        self.acciaCombo.setObjectName("acciaCombo")
        self.vboxlayout5.addWidget(self.acciaCombo)
        self.hboxlayout2.addLayout(self.vboxlayout5)
        self.hboxlayout1.addLayout(self.hboxlayout2)
        self.vboxlayout3.addWidget(self.provaBox)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout3.addItem(spacerItem)
        self.cavalloLabel = QtGui.QLabel(StrategiaProve)
        self.cavalloLabel.setWordWrap(False)
        self.cavalloLabel.setObjectName("cavalloLabel")
        self.vboxlayout3.addWidget(self.cavalloLabel)
        self.formaBar = QtGui.QProgressBar(StrategiaProve)
        self.formaBar.setProperty("value", 24)
        self.formaBar.setObjectName("formaBar")
        self.vboxlayout3.addWidget(self.formaBar)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout3.addItem(spacerItem1)
        self.hboxlayout.addLayout(self.vboxlayout3)
        self.vboxlayout1.addLayout(self.hboxlayout)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.hboxlayout3.addItem(spacerItem2)
        self.okButton = QtGui.QPushButton(StrategiaProve)
        self.okButton.setObjectName("okButton")
        self.hboxlayout3.addWidget(self.okButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.hboxlayout3.addItem(spacerItem3)
        self.cancelButton = QtGui.QPushButton(StrategiaProve)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout3.addWidget(self.cancelButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.hboxlayout3.addItem(spacerItem4)
        self.vboxlayout1.addLayout(self.hboxlayout3)
        self.vboxlayout.addLayout(self.vboxlayout1)

        self.retranslateUi(StrategiaProve)
        QtCore.QObject.connect(self.okButton, QtCore.SIGNAL("clicked()"), StrategiaProve.accept)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL("clicked()"), StrategiaProve.reject)
        QtCore.QMetaObject.connectSlotsByName(StrategiaProve)

    def retranslateUi(self, StrategiaProve):
        StrategiaProve.setWindowTitle(QtGui.QApplication.translate("StrategiaProve", "Strategia Prove", None, QtGui.QApplication.UnicodeUTF8))
        self.contradaLabel.setText(QtGui.QApplication.translate("StrategiaProve", "textLabel2", None, QtGui.QApplication.UnicodeUTF8))
        self.montaLabel.setText(QtGui.QApplication.translate("StrategiaProve", "textLabel2", None, QtGui.QApplication.UnicodeUTF8))
        self.provaBox.setTitle(QtGui.QApplication.translate("StrategiaProve", "Strategia Prove", None, QtGui.QApplication.UnicodeUTF8))
        self.primaLabel.setText(QtGui.QApplication.translate("StrategiaProve", "Prima Prova:", None, QtGui.QApplication.UnicodeUTF8))
        self.secondaLabel.setText(QtGui.QApplication.translate("StrategiaProve", "Seconda Prova:", None, QtGui.QApplication.UnicodeUTF8))
        self.terzaLabel.setText(QtGui.QApplication.translate("StrategiaProve", "Terza Prova:", None, QtGui.QApplication.UnicodeUTF8))
        self.quartaLabel.setText(QtGui.QApplication.translate("StrategiaProve", "Quarta Prova:", None, QtGui.QApplication.UnicodeUTF8))
        self.generaleLabel.setText(QtGui.QApplication.translate("StrategiaProve", "Prova Generale:", None, QtGui.QApplication.UnicodeUTF8))
        self.acciaLabel.setText(QtGui.QApplication.translate("StrategiaProve", "Provaccia:", None, QtGui.QApplication.UnicodeUTF8))
        self.cavalloLabel.setText(QtGui.QApplication.translate("StrategiaProve", "textLabel1", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("StrategiaProve", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("StrategiaProve", "Cancella", None, QtGui.QApplication.UnicodeUTF8))

